.gitignore
README.md
environments/package.py
requirements.txt
service/package.py
tasks.py

Can be used with: invoke build-service

Adds code that registers versions and git commits for builds

---

portal/package-lock.json
portal/package.json
portal/public/index.html
portal/src/main.js

Not render vue in IE11 or Legacy edge

---

portal/src/components/Materials/MaterialInfo/MaterialInfo.component.js
portal/src/components/Popup/SaveRating/SaveRating.component.js

See for example http://localhost:8080/materialen/wikiwijsmaken:70820 and give a rating

Save material rating in session storage

---

portal/src/components/Communities/PopularList/PopularList.component.html
portal/src/components/Communities/PopularList/PopularList.component.js
portal/src/pages/index.vue

- main__thems_and_communities block visible again, themes hidden
- moved main__thems_and_communities block below materials block
- fixed community name

Show communities on homepage again

---

portal/src/axios.js
portal/src/index.js
portal/src/plugins/README.md
portal/src/plugins/SocialSharing.js
portal/src/plugins/VueClipboard.js
portal/src/plugins/VueMasonry.js
portal/src/plugins/auth.js
portal/src/plugins/infiniteScroll.js
portal/src/store/modules/user.js

Removed very complex nuxt plugin loading. This didn't seem to have any benefit at all and was very hard to understand.

Remove weird nuxt plugin loading

---

portal/src/components/Materials/Materials.component.html
portal/src/components/Materials/Materials.component.less
portal/src/pages/collection.vue
portal/src/pages/index.vue
portal/src/styles/common.less

Refactored materials boxes on home to prepare for mobile responsiveness.
Removed the kriegel on home.

Cleanup materials on home

---

portal/src/components/Materials/Sidebar/Sidebar.component.less
portal/src/components/Popup/SaveRating/SaveRating.component.html
portal/src/components/Popup/SaveRating/SaveRating.component.js
portal/src/components/StarRating/StarRating.component.html
portal/src/components/StarRating/StarRating.component.js
portal/src/styles/forms.less

Displays the submit button only when a star rating is selected. This PR also centers the text in buttons

Show submit button when star rating is selected

---

deploy.py

Related to https://github.com/surfedushare/infra/pull/13

Update the task definition for clearlogins task on deploy

---

portal/public/index.html
portal/src/components/Collections/Collections.component.less
portal/src/components/FilterCategories/FilterCategories.component.less
portal/src/components/FilterCategories/Search/Search.component.less
portal/src/components/FilterCategories/Search/autosuggest.less
portal/src/components/InfoBlock/InfoBlock.less
portal/src/components/Keywords/Keywords.component.less
portal/src/components/MainFooter/MainFooter.component.less
portal/src/components/MainFooter/Menu/Menu.component.less
portal/src/components/MainHeader/MainHeader.component.html
portal/src/components/MainHeader/MainHeader.component.less
portal/src/components/Materials/MaterialInfo/MaterialInfo.component.less
portal/src/components/Materials/Materials.component.html
portal/src/components/Materials/Materials.component.less
portal/src/components/Themes/Themes.component.less
portal/src/pages/collection.vue
portal/src/pages/communities.vue
portal/src/pages/community.vue
portal/src/pages/how-does-it-work.vue
portal/src/pages/index.vue
portal/src/pages/material.vue
portal/src/pages/my/collections.vue
portal/src/pages/my/community.vue
portal/src/pages/my/privacy.vue
portal/src/pages/search.vue
portal/src/styles/common.less
service/surf/apps/materials/jinja2/portal/index.html

More compact styling and made it work on mobile phones.
I skipped the communities management part for now, because we will change it soon anyway.
You can best check it in your browser I guess 😉

More compact and responsive styling

---

portal/src/pages/communities.vue

Fixes bug: Can't navigate from /communities to  /my/communities and vice versa

Watch route change in communities component

---

portal/package-lock.json
portal/package.json
portal/src/components/HeaderBlock.vue
portal/src/components/InputFile/InputFile.component.html
portal/src/components/InputFile/InputFile.component.less
portal/src/components/InputFile/index.vue
portal/src/components/RichTextInput.vue
portal/src/main.js
portal/src/pages/communities.vue
portal/src/pages/how-does-it-work.vue
portal/src/pages/my/community.vue
portal/src/pages/my/privacy.vue

Also fixed the styling of the community page

Rich text editor for community description

---

portal/src/components/Materials/Sidebar/Sidebar.component.html
portal/src/components/Materials/Sidebar/Sidebar.component.js
portal/src/components/Multiselect/Multiselect.component.html
portal/src/components/Multiselect/Multiselect.component.js
portal/src/components/Multiselect/Multiselect.component.less

It was also broken, because the title is now depending on your locale.

Sort collections by title, depending on language

---

portal/src/components/Materials/MaterialInfo/MaterialInfo.component.html
portal/src/components/Materials/MaterialInfo/MaterialInfo.component.js
portal/src/components/Materials/Sidebar/Sidebar.component.html
portal/src/components/Materials/Sidebar/Sidebar.component.js
portal/src/components/Multiselect/Multiselect.component.js
portal/src/pages/material.vue

Displays the communities the material is in on the material page (was broken)

Display current communities

---

portal/src/axios.js
portal/src/components/ErrorWrapper.vue
portal/src/components/InputFile/InputFile.component.html
portal/src/components/InputFile/InputFile.component.js
portal/src/components/InputFile/InputFile.component.less
portal/src/components/InputLanguageWrapper.vue
portal/src/components/InputWithCounter.vue
portal/src/components/Popup/AddCollection/AddCollection.component.html
portal/src/components/Popup/AddCollection/AddCollection.component.js
portal/src/components/RichTextInput.vue
portal/src/components/switch-input.vue
portal/src/pages/my/community.vue

Implement the new community design.

Community design

---

portal/src/components/Materials/Materials.component.js
service/surf/apps/materials/utils.py

Oeps, had net iets teveel weggehaald.

Display disciplines in material list view

---

portal/src/pages/collection.vue

Fix javascript find to NOT use lodash syntax

---

portal/src/components/Collections/Collection/Collection.component.html
portal/src/components/Collections/Collection/Collection.component.js
portal/src/components/Collections/Collection/Collection.component.less
portal/src/components/Collections/Collections.component.html
portal/src/components/Collections/Collections.component.js
portal/src/components/Collections/Collections.component.less
portal/src/components/InputWithCounter.vue
portal/src/components/Materials/Materials.component.html
portal/src/components/Materials/Materials.component.js
portal/src/components/Popup/AddCollection/AddCollection.component.html
portal/src/components/Popup/AddCollection/AddCollection.component.js
portal/src/components/Popup/DeleteCollection/DeleteCollection.component.html
portal/src/pages/collection.vue
service/e2e_tests/test_collection_materials.py
service/e2e_tests/test_collections.py
service/surf/apps/materials/models.py

To do: fix sortable when collection has more than 10 materials

Improve collections

---

service/aws-container-definitions.json

Belongs to: https://github.com/surfedushare/infra/pull/24

Write logs to elasticsearch through firelens

---

portal/src/components/MainFooter/Menu/Menu.component.html

In mijn lokale admin omgeving heb ik een locale toegevoegd, maar hoe werkt dat ook weer om het overal goed te krijgen?

Add mailto contact in footer

---

service/surf/apps/materials/utils.py

De index moet ook opnieuw worden gemaakt. Mijn idee was om de huidige index weg te gooien en de code een nieuwe te laten maken

Better mapping for filters, add timestamp of search

---

harvester/core/models/datatypes/arrangement.py
harvester/core/tests/commands/push_es_index.py
harvester/core/tests/models/arrangement.py

Would otherwise lead to wrong links in search results

Fixes problems for frontend with external id

---

harvester/core/models/resources/basic.py

Fixes problem with AWS signature params disrupting cache

Tika speedup

---

commands/projects/harvester/invoke.py
environments/surfpol/configuration.py
harvester/harvester/management/commands/dump_harvester_data.py
harvester/harvester/management/commands/load_harvester_data.py
tasks.py

Not yet fully documented, but wanted to provide ways that can copy data from any environment to any environment

Devops improvements

---

commands/projects/service/fabric.py

Solves problem when logging in that people would not be subscribed to communities: https://www.pivotaltracker.com/story/show/175702060

Fixes create snapshot to create tables but exclude data

---

portal/src/components/Collections/Collection/Collection.component.less

Fix collection action bar on mobile

---

portal/src/components/MainFooter/MainFooter.component.less

https://www.pivotaltracker.com/story/show/175845859

Margin top on main footer

---

portal/src/components/Materials/Material/Material.vue
portal/src/components/Materials/Materials.component.less

Set icon is moved above of the material-main-info box

Reduce stretch material subinfo

---

portal/src/components/Materials/MaterialInfo/MaterialInfo.component.less
portal/src/components/Materials/MaterialSet/MaterialSet.vue

https://www.pivotaltracker.com/story/show/175909729

Remove set index

---

service/surf/apps/users/authentication.py

Dit is wel een goed voorbeeld van waarom ik een master branch handig vindt. Er is een probleem met logout via de admin (portal werkt wel). Nu kunnen we makkelijk de fix daarvoor op prod zetten via master, zonder dat Jelmer eerst alles op acc hoeft te accepteren.

Fixes logout through the admin

---

portal/src/components/Materials/Sidebar/Sidebar.component.js

Fix add material to collection in material detail view

---

commands/aws/ecs.py
commands/deploy/deploy.py
environments/acceptance/superuser.invoke.yml
environments/development/superuser.invoke.yml
environments/localhost/superuser.invoke.yml
environments/production/superuser.invoke.yml
harvester/aws-container-definitions.json

Goes together with a Terraform PR

Adds basic auth configuration to flower container

---

environments/acceptance/harvester/invoke.yml
environments/acceptance/invoke.yml
environments/development/harvester/invoke.yml
environments/development/invoke.yml
environments/localhost/invoke.yml
environments/production/harvester/invoke.yml
environments/production/invoke.yml
portal/src/components/Materials/MaterialInfo/MaterialInfo.component.html
portal/src/components/Materials/MaterialInfo/MaterialInfo.component.js
portal/src/components/Materials/MaterialInfo/MaterialInfo.component.less
portal/src/components/Materials/Sidebar/Sidebar.component.less
service/surf/settings/base.py
service/surf/vendor/elasticsearch/api.py

Moet nog op AWS testen, daar moeten de rechten om bij de bucket te kunnen nog worden ingesteld.

Display preview images

---

harvester/edurep/models.py
harvester/edurep/tests/__init__.py
harvester/edurep/tests/factories.py
harvester/edurep/tests/models.py
harvester/edurep/tests/utils.py
service/e2e_tests/base.py
service/surf/vendor/search/tests/tests_elastic_search.py

* Decompound search
* EdurepOAIPMH Resource
* Connect to new Sharekit in tests

Adds more tests

---

portal/src/components/Disciplines/Disciplines.component.js
portal/src/components/_helpers.js

Have been looking through the whole codebase, but I couldn't find the 'root cause'. A possible reason could be some url's are old and causing issues when navigating to it. Now when parsing the URL I check in what format it is and parse it in the right format. Also found an issue in the disciplines component, not sure if it is used anyway.

Fix an error in searching
